### PR TITLE
PG_CATCH when holding locks

### PR DESCRIPTION
**Pull request by yrashk**

### CODE REVIEW

**Review by mkindahl — COMMENTED** [review]
Looks good but it is a little unclear if this is a description of a problem or contains a way to solve a problem.

If it is the latter, it might be good to add an example to show proper usage.

If it is the former it might be a good idea to show a patch that solves the problem.

**Comment by steve-chavez** [comment]
My 2¢. This looks it fits a [how-to](https://docs.divio.com/documentation-system/how-to-guides/), in that:

- Solves a particular problem  ("How-to PG_CATCH when holding locks")
- It assumes previous knowledge (doesn't explain all the steps) 
- it's not repeatable (not a runnable example, unlike [tutorials](https://docs.divio.com/documentation-system/tutorials/#make-your-tutorial-repeatable)).

Perhaps [divio/diataxis](https://docs.divio.com/documentation-system/) structure can be adopted? Not sure if this is adequate for a book, but it could make merging contributions faster.

**Comment by yrashk** [comment]
The notion of "book" (at least in my mind) is highly superficial here.

I do agree that this chapter (article?) looks a lot more like a how-to.

**Comment by yrashk** [comment]
To note, there's some similarity to [DITA topics](https://help.adobe.com/en_US/framemaker/using/using-framemaker/user-guide/frm_structauthdita_sd_dita-topics.html)

I will merge this for now but any improvement changes are welcome in a follow-up!

**Pull request merged**
